mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  database: ${MYSQL_DATABASE}

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DATABASE}

server:
  port: ${SERVER_PORT}
  mode: ${SERVER_MODE}
  sentry_url: ${SENTRY_URL}
  uptrace_dns: ${UPTRACE_DNS}
  service_name: ${SERVICE_NAME}

grpc:
  oauth_url: ${GRPC_OAUTH_URL}
  workspace_url: ${GRPC_WORKSPACE_URL}
